version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=maza
      - MONGO_INITDB_ROOT_PASSWORD=polar
    ports:
      - 27017:27017
    restart: unless-stopped